modLoader="javafml"
loaderVersion="[46,)"
license="MIT"
issueTrackerURL="https://github.com/Flanks255/simply-graves/issues" #optional
[[mods]]
modId="simplygraves"
version="${file.jarVersion}"
displayName="Simply-Graves"
logoFile="examplemod.png"
credits=""
authors="Flanks255"
description='''
'''
