modLoader="javafml"
license="MIT"
issueTrackerURL="https://github.com/Flanks255/simply-graves/issues" #optional
[[mods]]
modId="simplygraves"
version="${mod_version}"
displayName="Simply-Graves"
logoFile=""
credits=""
authors="Flanks255"
description='''
'''
